### ISSUE TITLE
pass_clang::rename-fun/replace-undefined-function/return-void has encountered a bug

### ISSUE THREAD

**Issue by sendaoYan** [csmith-project/creduce#265]
```log
pass_clang::return-void has encountered a bug:
crashed: "/home/yansendao/tone/run/csmith/creduce-binary/libexec/clang_delta" --transformation=return-void --counter=1 /tmp/creduce-W8Elj5/test-creduce.c

Please consider tarring up /home/yansendao/creduce/aone-52722943/creduce_bug_000
and mailing it to creduce-bugs@flux.utah.edu and we will try to fix
the bug.
--
pass_clang::replace-undefined-function has encountered a bug:
crashed: "/home/yansendao/tone/run/csmith/creduce-binary/libexec/clang_delta" --transformation=replace-undefined-function --counter=1 /tmp/creduce-5XluQ6/test-creduce.c

Please consider tarring up /home/yansendao/creduce/aone-52722943/creduce_bug_001
and mailing it to creduce-bugs@flux.utah.edu and we will try to fix
the bug.
--
pass_clang::return-void has encountered a bug:
crashed: "/home/yansendao/tone/run/csmith/creduce-binary/libexec/clang_delta" --transformation=return-void --counter=1 /tmp/creduce-ytQQEX/test-creduce.c

Please consider tarring up /home/yansendao/creduce/aone-52722943/creduce_bug_002
and mailing it to creduce-bugs@flux.utah.edu and we will try to fix
the bug.
--
pass_clang::return-void has encountered a bug:
crashed: "/home/yansendao/tone/run/csmith/creduce-binary/libexec/clang_delta" --transformation=return-void --counter=1 /tmp/creduce-eDrGNV/test-creduce.c

Please consider tarring up /home/yansendao/creduce/aone-52722943/creduce_bug_003
and mailing it to creduce-bugs@flux.utah.edu and we will try to fix
the bug.
--
pass_clang::return-void has encountered a bug:
crashed: "/home/yansendao/tone/run/csmith/creduce-binary/libexec/clang_delta" --transformation=return-void --counter=1 /tmp/creduce-ut1Sfx/test-creduce.c

Please consider tarring up /home/yansendao/creduce/aone-52722943/creduce_bug_004
and mailing it to creduce-bugs@flux.utah.edu and we will try to fix
the bug.
--
pass_clang::return-void has encountered a bug:
crashed: "/home/yansendao/tone/run/csmith/creduce-binary/libexec/clang_delta" --transformation=return-void --counter=1 /tmp/creduce-nscQ6T/test-creduce.c

Please consider tarring up /home/yansendao/creduce/aone-52722943/creduce_bug_005
and mailing it to creduce-bugs@flux.utah.edu and we will try to fix
the bug.
--
pass_clang::rename-fun has encountered a bug:
crashed: "/home/yansendao/tone/run/csmith/creduce-binary/libexec/clang_delta" --transformation=rename-fun --counter=1 /tmp/creduce-_2SdTw/test-creduce.c

Please consider tarring up /home/yansendao/creduce/aone-52722943/creduce_bug_006
and mailing it to creduce-bugs@flux.utah.edu and we will try to fix
the bug.
```

[creduce_bug_003.zip](https://github.com/csmith-project/creduce/files/12995599/creduce_bug_003.zip)
[creduce_bug_004.zip](https://github.com/csmith-project/creduce/files/12995605/creduce_bug_004.zip)
[creduce_bug_005.zip](https://github.com/csmith-project/creduce/files/12995608/creduce_bug_005.zip)
[creduce_bug_006.zip](https://github.com/csmith-project/creduce/files/12995611/creduce_bug_006.zip)
[creduce_bug_000.zip](https://github.com/csmith-project/creduce/files/12995612/creduce_bug_000.zip)
[creduce_bug_001.zip](https://github.com/csmith-project/creduce/files/12995613/creduce_bug_001.zip)
[creduce_bug_002.zip](https://github.com/csmith-project/creduce/files/12995615/creduce_bug_002.zip)

**Comment by sendaoYan** [comment]
clang_delta: ReturnVoid.cpp:236: bool RVASTVisitor::rewriteFuncDecl(FunctionDecl *): Assertion `Offset >= 0' failed.

```
Program received signal SIGSEGV, Segmentation fault.
0x0000fffff2efd3a0 in (anonymous namespace)::RopePieceBTreeNode::erase(unsigned int, unsigned int) () from /home/yansendao/tone/run/csmith/creduce-binary/libexec/libclang-cpp.so.16
(gdb) bt
#0  0x0000fffff2efd3a0 in (anonymous namespace)::RopePieceBTreeNode::erase(unsigned int, unsigned int) () from /home/yansendao/tone/run/csmith/creduce-binary/libexec/libclang-cpp.so.16
#1  0x0000fffff2f0170c in clang::Rewriter::ReplaceText(clang::SourceLocation, unsigned int, llvm::StringRef) () from /home/yansendao/tone/run/csmith/creduce-binary/libexec/libclang-cpp.so.16
#2  0x0000aaaaadbcbc38 in RVASTVisitor::rewriteFuncDecl(clang::FunctionDecl*) ()
#3  0x0000aaaaadbcbd50 in RVASTVisitor::VisitFunctionDecl(clang::FunctionDecl*) ()
#4  0x0000aaaaadccc774 in clang::RecursiveASTVisitor<RVASTVisitor>::WalkUpFromFunctionDecl(clang::FunctionDecl*) ()
#5  0x0000aaaaadc57228 in clang::RecursiveASTVisitor<RVASTVisitor>::TraverseFunctionDecl(clang::FunctionDecl*) ()
#6  0x0000aaaaadbcdc20 in clang::RecursiveASTVisitor<RVASTVisitor>::TraverseDecl(clang::Decl*) ()
#7  0x0000aaaaadcb2c00 in clang::RecursiveASTVisitor<RVASTVisitor>::TraverseDeclContextHelper(clang::DeclContext*) ()
#8  0x0000aaaaadc5be30 in clang::RecursiveASTVisitor<RVASTVisitor>::TraverseTranslationUnitDecl(clang::TranslationUnitDecl*) ()
#9  0x0000aaaaadbce220 in clang::RecursiveASTVisitor<RVASTVisitor>::TraverseDecl(clang::Decl*) ()
#10 0x0000aaaaadbcb900 in ReturnVoid::HandleTranslationUnit(clang::ASTContext&) ()
#11 0x0000fffff1733038 in clang::ParseAST(clang::Sema&, bool, bool) () from /home/yansendao/tone/run/csmith/creduce-binary/libexec/libclang-cpp.so.16
#12 0x0000aaaaae997e58 in TransformationManager::doTransformation(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, int&) ()
#13 0x0000aaaaaaca034c in main ()
```
